services:
    web:
        image: nginx:latest
        platform: linux/amd64
        ports:
        - "80:80"
        volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
        - app
    app:
        build:
            context: ..
            dockerfile: .docker/php/Dockerfile
        volumes:
        - ..:/var/www/html
    db:
        image: mysql:8.0
        platform: linux/amd64
        volumes:
        - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: flutterwave